export const enum IpcChannelName {
  LibraryRead = "library:read",
  LibrarySave = "library:save",
  LibraryViewSettingsRead = "library:view-settings-read",
  LibraryViewSettingsSave = "library:view-settings-save",
  LibraryRootsList = "library:roots-list",
  LibraryRootOrderSet = "library:root-order-set",
  LibraryRootChooseAndScan = "library:root-choose-and-scan",
  LibraryDirectoryChooseAndImport = "library:directory-choose-and-import",
  LibraryRootScan = "library:root-scan",
  LibraryRootRemap = "library:root-remap",
  LibraryRootRemove = "library:root-remove",
  LibraryRootPurgeMissing = "library:root-purge-missing",
  LibraryRootWatchSet = "library:root-watch-set",
  LibraryExternalChanged = "library:external-changed",
  LibraryExternalValidate = "library:external-validate",
  StartupGalleryList = "startup-gallery:list",
  StartupGalleryImport = "startup-gallery:import",
  StartupGalleryImportFromClipboard = "startup-gallery:import-from-clipboard",
  StartupGalleryRemove = "startup-gallery:remove",
  StartupGalleryReset = "startup-gallery:reset",
  ImageImportFiles = "image:import-files",
  ImageImportBuffers = "image:import-buffers",
  ImageImportGenerated = "image:import-generated",
  ImageImportFilesForItem = "image:import-files-for-item",
  ImageImportProgress = "image:import-progress",
  ImageImportCancel = "image:import-cancel",
  WordDocumentImport = "word:import-document",
  ImageImportFromClipboard = "image:import-from-clipboard",
  ImageImportClipboardForItem = "image:import-clipboard-for-item",
  ImageRemoteMaterialDownload = "image:remote-material-download",
  ImageCopy = "image:copy",
  ImageExport = "image:export",
  ImageThumbnailResolve = "image:thumbnail-resolve",
  ImageThumbnailsResolve = "image:thumbnails-resolve",
  ImageGetFileSize = "image:get-file-size",
  ClipboardWriteText = "clipboard:write-text",
  ClipboardReadText = "clipboard:read-text",
  ClipboardReadImage = "clipboard:read-image",
  CanvasReferenceImageSave = "canvas:reference-image-save",
  CanvasReferenceImageRead = "canvas:reference-image-read",
  CanvasReferenceImageRemove = "canvas:reference-image-remove",
  LexiconImageImport = "lexicon:image-import",
  LexiconExport = "lexicon:export-json",
  LexiconImport = "lexicon:import-json",
  ItemDelete = "item:delete",
  VideoFramesGenerate = "video:frames-generate",
  VideoReferenceImagesImport = "video:reference-images-import",
  VideoReferenceImageDelete = "video:reference-image-delete",
  VideoReferenceImageImportClipboard = "video:reference-image-import-clipboard",
  VideoReferenceImageImportUrl = "video:reference-image-import-url",
  ArchiveExportZip = "archive:export-zip",
  ArchiveImportZip = "archive:import-zip",
  AiSettingsRead = "ai:settings-read",
  AiSettingsSave = "ai:settings-save",
  AiApiKeyCopy = "ai:api-key-copy",
  AiApiKeyRead = "ai:api-key-read",
  AiSettingsTest = "ai:settings-test",
  AiModelsList = "ai:models-list",
  AiAnalyzePrompt = "ai:analyze-prompt",
  AiOptimizePrompt = "ai:optimize-prompt",
  AiSummarizePromptTitle = "ai:summarize-prompt-title",
  AiTranslatePrompt = "ai:translate-prompt",
  AiReverseImagePrompt = "ai:reverse-image-prompt",
  AiGenerateImages = "ai:generate-images",
  DoubaoWebCanvasPrepare = "doubao-web:prepare",
  DoubaoWebCanvasAuth = "doubao-web:auth",
  DoubaoWebCanvasBounds = "doubao-web:bounds",
  DoubaoWebCanvasShow = "doubao-web:show",
  DoubaoWebCanvasHide = "doubao-web:hide",
  DoubaoWebCanvasGenerate = "doubao-web:generate",
  ProxySettingsRead = "proxy:settings-read",
  ProxySettingsSave = "proxy:settings-save",
  ProxySettingsTest = "proxy:settings-test",
  ProxySettingsDetect = "proxy:settings-detect",
  AppAccelerationStatusRead = "app:acceleration-status-read",
  AppAccelerationSettingsSave = "app:acceleration-settings-save",
  AppOpenExternalUrl = "app:open-external-url",
  AppOpenDataDirectory = "app:open-data-directory",
  AppUpdateCheck = "app:update-check",
  AppRendererReady = "app:renderer-ready",
  AppStartupScreenReady = "app:startup-screen-ready",
  AppStartupLog = "app:startup-log",
  BatchDeduplicateScan = "batch:deduplicate-scan",
  BatchCompressImages = "batch:compress-images",
  BatchCompressProgress = "batch:compress-progress",
  BatchCompressVideos = "batch:compress-videos",
  BatchCompressVideoProgress = "batch:compress-video-progress",
  BatchCancelCompress = "batch:cancel-compress",
  ModuleCheckInstalled = "module:check-installed",
  ModuleInstallLocal = "module:install-local",
  ModuleInstallGithub = "module:install-github",
  ModuleInstallProgress = "module:install-progress",
  ComponentFfmpegInstallDownload = "component:ffmpeg-install-download",
  ComponentFfmpegInstallLocal = "component:ffmpeg-install-local",
  ComponentFfmpegInstallProgress = "component:ffmpeg-install-progress",
  WindowMinimize = "window:minimize",
  WindowMaximizeToggle = "window:maximize-toggle",
  WindowClose = "window:close",
  WindowIsMaximized = "window:is-maximized",
  WindowMaximizeChange = "window:maximize-change",
  LogExport = "log:export",
}

export const ipcChannels = {
  libraryRead: IpcChannelName.LibraryRead,
  librarySave: IpcChannelName.LibrarySave,
  libraryViewSettingsRead: IpcChannelName.LibraryViewSettingsRead,
  libraryViewSettingsSave: IpcChannelName.LibraryViewSettingsSave,
  libraryRootsList: IpcChannelName.LibraryRootsList,
  libraryRootOrderSet: IpcChannelName.LibraryRootOrderSet,
  libraryRootChooseAndScan: IpcChannelName.LibraryRootChooseAndScan,
  libraryDirectoryChooseAndImport: IpcChannelName.LibraryDirectoryChooseAndImport,
  libraryRootScan: IpcChannelName.LibraryRootScan,
  libraryRootRemap: IpcChannelName.LibraryRootRemap,
  libraryRootRemove: IpcChannelName.LibraryRootRemove,
  libraryRootPurgeMissing: IpcChannelName.LibraryRootPurgeMissing,
  libraryRootWatchSet: IpcChannelName.LibraryRootWatchSet,
  libraryExternalChanged: IpcChannelName.LibraryExternalChanged,
  libraryExternalValidate: IpcChannelName.LibraryExternalValidate,
  startupGalleryList: IpcChannelName.StartupGalleryList,
  startupGalleryImport: IpcChannelName.StartupGalleryImport,
  startupGalleryImportFromClipboard: IpcChannelName.StartupGalleryImportFromClipboard,
  startupGalleryRemove: IpcChannelName.StartupGalleryRemove,
  startupGalleryReset: IpcChannelName.StartupGalleryReset,
  imageImportFiles: IpcChannelName.ImageImportFiles,
  imageImportFilesForItem: IpcChannelName.ImageImportFilesForItem,
  imageImportBuffers: IpcChannelName.ImageImportBuffers,
  imageImportGenerated: IpcChannelName.ImageImportGenerated,
  imageImportProgress: IpcChannelName.ImageImportProgress,
  imageImportCancel: IpcChannelName.ImageImportCancel,
  wordDocumentImport: IpcChannelName.WordDocumentImport,
  imageImportFromClipboard: IpcChannelName.ImageImportFromClipboard,
  imageImportClipboardForItem: IpcChannelName.ImageImportClipboardForItem,
  imageRemoteMaterialDownload: IpcChannelName.ImageRemoteMaterialDownload,
  imageCopy: IpcChannelName.ImageCopy,
  imageExport: IpcChannelName.ImageExport,
  imageThumbnailResolve: IpcChannelName.ImageThumbnailResolve,
  imageThumbnailsResolve: IpcChannelName.ImageThumbnailsResolve,
  imageGetFileSize: IpcChannelName.ImageGetFileSize,
  clipboardWriteText: IpcChannelName.ClipboardWriteText,
  clipboardReadText: IpcChannelName.ClipboardReadText,
  clipboardReadImage: IpcChannelName.ClipboardReadImage,
  canvasReferenceImageSave: IpcChannelName.CanvasReferenceImageSave,
  canvasReferenceImageRead: IpcChannelName.CanvasReferenceImageRead,
  canvasReferenceImageRemove: IpcChannelName.CanvasReferenceImageRemove,
  lexiconImageImport: IpcChannelName.LexiconImageImport,
  lexiconExport: IpcChannelName.LexiconExport,
  lexiconImport: IpcChannelName.LexiconImport,
  itemDelete: IpcChannelName.ItemDelete,
  videoFramesGenerate: IpcChannelName.VideoFramesGenerate,
  videoReferenceImagesImport: IpcChannelName.VideoReferenceImagesImport,
  videoReferenceImageDelete: IpcChannelName.VideoReferenceImageDelete,
  videoReferenceImageImportClipboard: IpcChannelName.VideoReferenceImageImportClipboard,
  videoReferenceImageImportUrl: IpcChannelName.VideoReferenceImageImportUrl,
  archiveExportZip: IpcChannelName.ArchiveExportZip,
  archiveImportZip: IpcChannelName.ArchiveImportZip,
  aiSettingsRead: IpcChannelName.AiSettingsRead,
  aiSettingsSave: IpcChannelName.AiSettingsSave,
  aiApiKeyCopy: IpcChannelName.AiApiKeyCopy,
  aiApiKeyRead: IpcChannelName.AiApiKeyRead,
  aiSettingsTest: IpcChannelName.AiSettingsTest,
  aiModelsList: IpcChannelName.AiModelsList,
  aiAnalyzePrompt: IpcChannelName.AiAnalyzePrompt,
  aiOptimizePrompt: IpcChannelName.AiOptimizePrompt,
  aiSummarizePromptTitle: IpcChannelName.AiSummarizePromptTitle,
  aiTranslatePrompt: IpcChannelName.AiTranslatePrompt,
  aiReverseImagePrompt: IpcChannelName.AiReverseImagePrompt,
  aiGenerateImages: IpcChannelName.AiGenerateImages,
  doubaoWebCanvasPrepare: IpcChannelName.DoubaoWebCanvasPrepare,
  doubaoWebCanvasAuth: IpcChannelName.DoubaoWebCanvasAuth,
  doubaoWebCanvasBounds: IpcChannelName.DoubaoWebCanvasBounds,
  doubaoWebCanvasShow: IpcChannelName.DoubaoWebCanvasShow,
  doubaoWebCanvasHide: IpcChannelName.DoubaoWebCanvasHide,
  doubaoWebCanvasGenerate: IpcChannelName.DoubaoWebCanvasGenerate,
  proxySettingsRead: IpcChannelName.ProxySettingsRead,
  proxySettingsSave: IpcChannelName.ProxySettingsSave,
  proxySettingsTest: IpcChannelName.ProxySettingsTest,
  proxySettingsDetect: IpcChannelName.ProxySettingsDetect,
  appAccelerationStatusRead: IpcChannelName.AppAccelerationStatusRead,
  appAccelerationSettingsSave: IpcChannelName.AppAccelerationSettingsSave,
  appOpenExternalUrl: IpcChannelName.AppOpenExternalUrl,
  appOpenDataDirectory: IpcChannelName.AppOpenDataDirectory,
  appUpdateCheck: IpcChannelName.AppUpdateCheck,
  appRendererReady: IpcChannelName.AppRendererReady,
  appStartupScreenReady: IpcChannelName.AppStartupScreenReady,
  appStartupLog: IpcChannelName.AppStartupLog,
  batchDeduplicateScan: IpcChannelName.BatchDeduplicateScan,
  batchCompressImages: IpcChannelName.BatchCompressImages,
  batchCompressProgress: IpcChannelName.BatchCompressProgress,
  batchCompressVideos: IpcChannelName.BatchCompressVideos,
  batchCompressVideoProgress: IpcChannelName.BatchCompressVideoProgress,
  batchCancelCompress: IpcChannelName.BatchCancelCompress,
  moduleCheckInstalled: IpcChannelName.ModuleCheckInstalled,
  moduleInstallLocal: IpcChannelName.ModuleInstallLocal,
  moduleInstallGithub: IpcChannelName.ModuleInstallGithub,
  moduleInstallProgress: IpcChannelName.ModuleInstallProgress,
  componentFfmpegInstallDownload: IpcChannelName.ComponentFfmpegInstallDownload,
  componentFfmpegInstallLocal: IpcChannelName.ComponentFfmpegInstallLocal,
  componentFfmpegInstallProgress: IpcChannelName.ComponentFfmpegInstallProgress,
  windowMinimize: IpcChannelName.WindowMinimize,
  windowMaximizeToggle: IpcChannelName.WindowMaximizeToggle,
  windowClose: IpcChannelName.WindowClose,
  windowIsMaximized: IpcChannelName.WindowIsMaximized,
  windowMaximizeChange: IpcChannelName.WindowMaximizeChange,
  logExport: IpcChannelName.LogExport,
} as const;

export type IpcChannel = (typeof ipcChannels)[keyof typeof ipcChannels];
