export const enum IpcChannelName {
  LibraryRead = "library:read",
  LibrarySave = "library:save",
  LibraryViewSettingsRead = "library:view-settings-read",
  LibraryViewSettingsSave = "library:view-settings-save",
  StartupGalleryList = "startup-gallery:list",
  StartupGalleryImport = "startup-gallery:import",
  StartupGalleryImportFromClipboard = "startup-gallery:import-from-clipboard",
  StartupGalleryRemove = "startup-gallery:remove",
  StartupGalleryReset = "startup-gallery:reset",
  ImageImportFiles = "image:import-files",
  ImageImportBuffers = "image:import-buffers",
  ImageImportFilesForItem = "image:import-files-for-item",
  ImageImportProgress = "image:import-progress",
  ImageImportCancel = "image:import-cancel",
  WordDocumentImport = "word:import-document",
  ImageImportFromClipboard = "image:import-from-clipboard",
  ImageImportClipboardForItem = "image:import-clipboard-for-item",
  ImageRemoteMaterialDownload = "image:remote-material-download",
  ImageCopy = "image:copy",
  ImageExport = "image:export",
  ImageThumbnailResolve = "image:thumbnail-resolve",
  ImageThumbnailsResolve = "image:thumbnails-resolve",
  ClipboardWriteText = "clipboard:write-text",
  LexiconImageImport = "lexicon:image-import",
  LexiconExport = "lexicon:export-json",
  LexiconImport = "lexicon:import-json",
  ItemDelete = "item:delete",
  VideoFramesGenerate = "video:frames-generate",
  VideoReferenceImagesImport = "video:reference-images-import",
  VideoReferenceImageDelete = "video:reference-image-delete",
  VideoReferenceImageImportClipboard = "video:reference-image-import-clipboard",
  VideoReferenceImageImportUrl = "video:reference-image-import-url",
  ArchiveExportZip = "archive:export-zip",
  ArchiveImportZip = "archive:import-zip",
  AiSettingsRead = "ai:settings-read",
  AiSettingsSave = "ai:settings-save",
  AiApiKeyCopy = "ai:api-key-copy",
  AiSettingsTest = "ai:settings-test",
  AiModelsList = "ai:models-list",
  AiAnalyzePrompt = "ai:analyze-prompt",
  AiOptimizePrompt = "ai:optimize-prompt",
  AiTranslatePrompt = "ai:translate-prompt",
  AiReverseImagePrompt = "ai:reverse-image-prompt",
  ProxySettingsRead = "proxy:settings-read",
  ProxySettingsSave = "proxy:settings-save",
  ProxySettingsTest = "proxy:settings-test",
  ProxySettingsDetect = "proxy:settings-detect",
  AppAccelerationStatusRead = "app:acceleration-status-read",
  AppAccelerationSettingsSave = "app:acceleration-settings-save",
  AppOpenExternalUrl = "app:open-external-url",
  AppUpdateCheck = "app:update-check",
  AppRendererReady = "app:renderer-ready",
  AppStartupScreenReady = "app:startup-screen-ready",
  AppStartupLog = "app:startup-log",
  BatchDeduplicateScan = "batch:deduplicate-scan",
  BatchCompressImages = "batch:compress-images",
  BatchCompressProgress = "batch:compress-progress",
  BatchCompressVideos = "batch:compress-videos",
  BatchCompressVideoProgress = "batch:compress-video-progress",
  BatchCancelCompress = "batch:cancel-compress",
  ModuleCheckInstalled = "module:check-installed",
  ModuleInstallLocal = "module:install-local",
  ModuleInstallGithub = "module:install-github",
  ModuleInstallProgress = "module:install-progress",
  WindowMinimize = "window:minimize",
  WindowMaximizeToggle = "window:maximize-toggle",
  WindowClose = "window:close",
  WindowIsMaximized = "window:is-maximized",
  WindowMaximizeChange = "window:maximize-change",
  LogExport = "log:export",
}

export const ipcChannels = {
  libraryRead: IpcChannelName.LibraryRead,
  librarySave: IpcChannelName.LibrarySave,
  libraryViewSettingsRead: IpcChannelName.LibraryViewSettingsRead,
  libraryViewSettingsSave: IpcChannelName.LibraryViewSettingsSave,
  startupGalleryList: IpcChannelName.StartupGalleryList,
  startupGalleryImport: IpcChannelName.StartupGalleryImport,
  startupGalleryImportFromClipboard: IpcChannelName.StartupGalleryImportFromClipboard,
  startupGalleryRemove: IpcChannelName.StartupGalleryRemove,
  startupGalleryReset: IpcChannelName.StartupGalleryReset,
  imageImportFiles: IpcChannelName.ImageImportFiles,
  imageImportFilesForItem: IpcChannelName.ImageImportFilesForItem,
  imageImportBuffers: IpcChannelName.ImageImportBuffers,
  imageImportProgress: IpcChannelName.ImageImportProgress,
  imageImportCancel: IpcChannelName.ImageImportCancel,
  wordDocumentImport: IpcChannelName.WordDocumentImport,
  imageImportFromClipboard: IpcChannelName.ImageImportFromClipboard,
  imageImportClipboardForItem: IpcChannelName.ImageImportClipboardForItem,
  imageRemoteMaterialDownload: IpcChannelName.ImageRemoteMaterialDownload,
  imageCopy: IpcChannelName.ImageCopy,
  imageExport: IpcChannelName.ImageExport,
  imageThumbnailResolve: IpcChannelName.ImageThumbnailResolve,
  imageThumbnailsResolve: IpcChannelName.ImageThumbnailsResolve,
  clipboardWriteText: IpcChannelName.ClipboardWriteText,
  lexiconImageImport: IpcChannelName.LexiconImageImport,
  lexiconExport: IpcChannelName.LexiconExport,
  lexiconImport: IpcChannelName.LexiconImport,
  itemDelete: IpcChannelName.ItemDelete,
  videoFramesGenerate: IpcChannelName.VideoFramesGenerate,
  videoReferenceImagesImport: IpcChannelName.VideoReferenceImagesImport,
  videoReferenceImageDelete: IpcChannelName.VideoReferenceImageDelete,
  videoReferenceImageImportClipboard: IpcChannelName.VideoReferenceImageImportClipboard,
  videoReferenceImageImportUrl: IpcChannelName.VideoReferenceImageImportUrl,
  archiveExportZip: IpcChannelName.ArchiveExportZip,
  archiveImportZip: IpcChannelName.ArchiveImportZip,
  aiSettingsRead: IpcChannelName.AiSettingsRead,
  aiSettingsSave: IpcChannelName.AiSettingsSave,
  aiApiKeyCopy: IpcChannelName.AiApiKeyCopy,
  aiSettingsTest: IpcChannelName.AiSettingsTest,
  aiModelsList: IpcChannelName.AiModelsList,
  aiAnalyzePrompt: IpcChannelName.AiAnalyzePrompt,
  aiOptimizePrompt: IpcChannelName.AiOptimizePrompt,
  aiTranslatePrompt: IpcChannelName.AiTranslatePrompt,
  aiReverseImagePrompt: IpcChannelName.AiReverseImagePrompt,
  proxySettingsRead: IpcChannelName.ProxySettingsRead,
  proxySettingsSave: IpcChannelName.ProxySettingsSave,
  proxySettingsTest: IpcChannelName.ProxySettingsTest,
  proxySettingsDetect: IpcChannelName.ProxySettingsDetect,
  appAccelerationStatusRead: IpcChannelName.AppAccelerationStatusRead,
  appAccelerationSettingsSave: IpcChannelName.AppAccelerationSettingsSave,
  appOpenExternalUrl: IpcChannelName.AppOpenExternalUrl,
  appUpdateCheck: IpcChannelName.AppUpdateCheck,
  appRendererReady: IpcChannelName.AppRendererReady,
  appStartupScreenReady: IpcChannelName.AppStartupScreenReady,
  appStartupLog: IpcChannelName.AppStartupLog,
  batchDeduplicateScan: IpcChannelName.BatchDeduplicateScan,
  batchCompressImages: IpcChannelName.BatchCompressImages,
  batchCompressProgress: IpcChannelName.BatchCompressProgress,
  batchCompressVideos: IpcChannelName.BatchCompressVideos,
  batchCompressVideoProgress: IpcChannelName.BatchCompressVideoProgress,
  batchCancelCompress: IpcChannelName.BatchCancelCompress,
  moduleCheckInstalled: IpcChannelName.ModuleCheckInstalled,
  moduleInstallLocal: IpcChannelName.ModuleInstallLocal,
  moduleInstallGithub: IpcChannelName.ModuleInstallGithub,
  moduleInstallProgress: IpcChannelName.ModuleInstallProgress,
  windowMinimize: IpcChannelName.WindowMinimize,
  windowMaximizeToggle: IpcChannelName.WindowMaximizeToggle,
  windowClose: IpcChannelName.WindowClose,
  windowIsMaximized: IpcChannelName.WindowIsMaximized,
  windowMaximizeChange: IpcChannelName.WindowMaximizeChange,
  logExport: IpcChannelName.LogExport,
} as const;

export type IpcChannel = (typeof ipcChannels)[keyof typeof ipcChannels];
